" Enable advanced VIM features by default
set nocp

" Pathogen
call pathogen#infect()
call pathogen#helptags()

" Turn on syntax hightlighting
syntax enable

" Highlight C whitespace errors
let c_space_errors=1

" Enable filetype plugins
filetype plugin on

map <C-L> :!ctags -R --c++-kinds=+p --fields=+iaS --extra=+q .<CR><CR>
set tags=~/.vim/stdtags,tags,.tags,../tags

" If you prefer the Omni-Completion tip window to close when a selection is
" " made, these lines close it on movement in insert mode or when leaving
" " insert mode
autocmd CursorMovedI * if pumvisible() == 0|pclose|endif
autocmd InsertLeave * if pumvisible() == 0|pclose|endif

" Remove trailing spaces binding
map <F12> :call TrimWhiteSpace()<CR>
function! TrimWhiteSpace()
  %s/\s*$//
  ''
endfunction

function! UseSpaces()
  set expandtab
  set tabstop=4
  set shiftwidth=4
  set smartindent
endfunction

function! UseTabs()
  set noexpandtab
  set smartindent
endfunction

" Spell check binding
map ^S :w!<CR>:!aspell check %<CR>:e! %<CR>

" Syntastic Global Options
let g:syntastic_check_on_open=1
let g:syntastic_enable_signs=1
let g:syntastic_error_symbol='✗'
let g:syntastic_cpp_check_header=1
let g:syntastic_cpp_auto_refresh_includes=1
let g:syntastic_cpp_compiler='g++'
let g:syntastic_python_checker='pyflakes'
let g:syntastic_sh_checker='checkbashisms'
